### ISSUE TITLE
would like to speak with you about project

### ISSUE THREAD

**Issue by classBabacar** [niknakz/inhouse-scrims#38]
Hi, I would like to speak with you about your project, if you have time.

**Comment by niknakz** [comment]
@classBabacar hey sorry just now seeing this, whats up?

**Comment by classBabacar** [comment]
Hey, so we extended mr.tolkien's inhouse bot(https://github.com/mrtolkien/inhouse_bot) to (https://github.com/adamschachne/inhouse_bot), but its flawed in the sense of the internal ranking system and we wanted to pivot to use solo queue ranks to form more balanced teams and came to find this repo since helps solve the problem pretty well.

So basically, we were asking if it would be ok to take your code logic and add it to our project?

Also, if you want you can join us making the bot better as well.

**Comment by niknakz** [comment]
@classBabacar yeah for sure take whatever you need. You might want to revisit the [MMR values](https://github.com/niknakz/inhouse-scrims/blob/main/module/src/index.ts#L3), I based them off the [season 2 public MMR values](https://leagueoflegends.fandom.com/wiki/Elo_rating_system) and scaled up to account for the new ranks but its probably not ideal. Also you might want some way to override the ranks you get from the riot api to be able to account for smurf accounts (which is why I decided not to integrate and require manual entry as most of my friend group has multiple accounts)

**Comment by classBabacar** [comment]
Cool thanks. @niknakz gonna close the issue now.
